"""Added Foreign key

Revision ID: 023357ddd7db
Revises: 2ca8bea8d03f
Create Date: 2023-10-13 12:38:10.089961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023357ddd7db'
down_revision = '2ca8bea8d03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
