"""It adds columns table users

Revision ID: 610c7f0207b6
Revises: 
Create Date: 2023-10-10 10:28:55.934391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610c7f0207b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(length=500), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('date_added')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
